guest = ['mum', 'dad', 'sister']
inv = 'I invite you '
for i in guest:
	print('I invite you ' + i.title())

print("\nHe won't be able to come is " +guest[1].title())
del guest[1]
guest.insert(1,'diana')
print(guest)
print('\nI invite you ' + guest[0].title() + '!')
print('I invite you ' + guest[1].title() + '!')
print('I invite you ' + guest[2].title() + '!')
print('Lists guest expanding!')
guest.insert(0,'messi')
guest.insert(2,'serg')
guest.append('petr')
print(guest)
print('\nI invite you ' + guest[0].title() + '!')
print('I invite you ' + guest[1].title() + '!')
print('I invite you ' + guest[2].title() + '!')
print('I invite you ' + guest[3].title() + '!')
print('I invite you ' + guest[4].title() + '!')
print('I invite you ' + guest[5].title() + '!')
print(len(guest))
print('I invite only 2 guest')
last_guest_del0 = guest.pop()
print('Sorry ' + last_guest_del0.title())
print(guest)
last_guest_del1 = guest.pop()
print('Sorry ' + last_guest_del1.title())
print(guest)
last_guest_del2 = guest.pop()
print('Sorry ' + last_guest_del2.title())
print(guest)
last_guest_del3 = guest.pop()
print('Sorry ' + last_guest_del3.title())
print(guest)
print('Hi!' + guest[0].title() + ',he offer is valid!')
print('Hi!' + guest[1].title() + ',he offer is valid!')
del guest[0]
del guest[0]
print(guest)
